### ISSUE TITLE
Arch/visualStudioStructuredSolution.upy gets stuck in an infinite loop while running on Notepad.sln

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/plugins#2]
Using the Notepad++ open source project (https://github.com/notepad-plus-plus/notepad-plus-plus), I tried to run Arch/visualStudioStructuredSolution.upy on Notepad.sln

Automatic architecture ran until Windows refused to allocate more memory.

**Comment by nstander** [comment]
@kylejacksonb Please test this again. The infinite loop should be fixed, but my Mac was not resolving the file paths correctly so please check that the paths work on Windows as expected. If the file paths aren't working, then the architecture won't appear since it is empty.

@hackhaslam Is it possible to show the automatic architecture when it's turned on even if it is empty. It's confusing to turn it on and have no error and no result.

**Comment by hackhaslam** [comment]
> @hackhaslam Is it possible to show the automatic architecture when it's turned on even if it is empty. It's confusing to turn it on and have no error and no result.

That makes sense. I'll make that change.

**Comment by hackhaslam** [comment]
> @hackhaslam Is it possible to show the automatic architecture when it's turned on even if it is empty. It's confusing to turn it on and have no error and no result.

This is done in stinb/sti@033c04313894671d3e42f0b6febb5fe4a5e9350d.
